microservices:
  products:
    server:
      host: localhost
      port: 8081
    database:
      host: localhost
      port: 27017

app:
  cache1:
    max-items: 100
    item-size: 64
  cache2:
    max-items: 200
    item-size: 80