swagger: '2.0'
info:
  description: Esta es la definicion de la api de ShopTool para microservicios de producto.
  version: 1.0.0
  title: Definicion de apis de ShopTool
  contact:
    email: rubentxu74@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8081'
basePath: /api
schemes:
  - http
paths:
  /product/command/create:
    post:
      tags:
        - Comandos
      summary: Crea un nuevo producto
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            CreateProductCommand
          required: true
          schema:
            $ref: '#/definitions/CreateProductCommand'
      responses:
        '400':
          description: Comando no valido
  /product/command/remove:
    post:
      tags:
        - Comandos
      summary: Elimina un nuevo producto
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            DeleteProductCommand
          required: true
          schema:
            $ref: '#/definitions/DeleteProductCommand'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/command/prodlang/add:
    post:
      tags:
        - Comandos
      summary: Añade una definicion de idioma al producto
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            AddProductLangCommand, el id es del producto
          required: true
          schema:
            $ref: '#/definitions/ProductLang'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/command/prodlang/update:
    post:
      tags:
        - Comandos
      summary: Actualiza una definicion en un idioma del producto
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            UpdateProductLangCommand, el id es del producto
          required: true
          schema:
            $ref: '#/definitions/ProductLang'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/command/prodlang/remove:
    post:
      tags:
        - Comandos
      summary: 'Elimina una definicion en un idioma del producto, el id es del producto'
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            RemoveProductLangCommand, el id es del producto
          required: true
          schema:
            $ref: '#/definitions/RemoveProductLangCommand'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/command/availabilityConfig:
    post:
      tags:
        - Comandos
      summary: 'Configura la disponibilidad del producto, el id es del producto'
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            SetAvailabilityCommand, el id es del producto
          required: true
          schema:
            $ref: '#/definitions/SetAvailabilityCommand'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/:
    get:
      tags:
        - Product
      summary: Consulta los productos disponibles
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: operacion exitosa
        '404':
          description: recursos no encontrados
  '/product/{productId}':
    get:
      tags:
        - Product
      summary: Consulta un producto por su id
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: productId
          required: true
          description: identificador del producto
          schema:
            type: string
      responses:
        '200':
          description: operacion exitosa
        '404':
          description: recursos no encontrados
definitions:
  CreateProductCommand:
    type: object
    properties:
      reference:
        type: string
      ean_13:
        type: string
      isbn:
        type: string
      upc:
        type: string
  DeleteProductCommand:
    type: object
    properties:
      id:
        type: string
        description: id del producto
  RemoveProductLangCommand:
    type: object
    properties:
      id:
        type: string
        description: id del producto
      lang_code:
        type: string
  SetAvailabilityCommand:
    type: object
    properties:
      id:
        type: string
        description: id del producto
      quantity:
        type: integer
      minimal_quantity:
        type: integer
      online_only:
        type: boolean
      on_sale:
        type: boolean
      out_of_stock:
        type: boolean
      active:
        type: boolean
      available_for_order:
        type: boolean
      available_date:
        type: string
      visibility:
        type: string
        enum:
          - CATALOG
          - SEARCH
          - NONE
          - BOTH
      date_add:
        type: string
      date_upd:
        type: string
      quantity_discount:
        type: boolean
  ProductLang:
    type: object
    properties:
      id:
        type: string
        description: id del producto
      name:
        type: string
      description:
        type: string
      description_short:
        type: string
      link_rewrite:
        type: string
      meta_description:
        type: string
      meta_keywords:
        type: string
      meta_title:
        type: string
      available_now:
        type: string
      available_later:
        type: string
      lang_code:
        type: string
        description: codigo del idioma
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
