swagger: '2.0'
info:
  description: Esta es la definicion de la api de ShopTool para microservicios de producto.
  version: 1.0.0
  title: Definicion de apis de ShopTool
  contact:
    email: rubentxu74@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8081'
basePath: /api
schemes:
  - http
paths:
  /product/command/create:
    post:
      tags:
        - Comandos
      summary: Crea un nuevo producto
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            CreateProductCommand
          required: true
          schema:
            $ref: '#/definitions/CreateProductCommand'
      responses:
        '400':
          description: Comando no valido
  /product/command/remove:
    post:
      tags:
        - Comandos
      summary: Elimina un nuevo producto
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            DeleteProductCommand
          required: true
          schema:
            $ref: '#/definitions/DeleteProductCommand'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/command/prodlang/add:
    post:
      tags:
        - Comandos
      summary: Añade una definicion de idioma al producto
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            AddProductLangCommand, el id es del producto
          required: true
          schema:
            $ref: '#/definitions/ProductLang'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/command/prodlang/update:
    post:
      tags:
        - Comandos
      summary: Actualiza una definicion en un idioma del producto
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            UpdateProductLangCommand, el id es del producto
          required: true
          schema:
            $ref: '#/definitions/ProductLang'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/command/prodlang/remove:
    post:
      tags:
        - Comandos
      summary: 'Elimina una definicion en un idioma del producto, el id es del producto'
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            RemoveProductLangCommand, el id es del producto
          required: true
          schema:
            $ref: '#/definitions/RemoveProductLangCommand'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/command/availabilityConfig:
    post:
      tags:
        - Comandos
      summary: 'Configura la disponibilidad del producto, el id es del producto'
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            SetAvailabilityCommand, el id es del producto
          required: true
          schema:
            $ref: '#/definitions/SetAvailabilityCommand'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/command/transportSpecificationConfig:
    post:
      tags:
        - Comandos
      summary: >-
        Configura la especificacion de transporte del producto, el id es del
        producto
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            SetTransportSpecificationCommand, el id es del producto
          required: true
          schema:
            $ref: '#/definitions/SetTransportSpecificationCommand'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/command/transport/add:
    post:
      tags:
        - Comandos
      summary: 'Agrega un transportista al producto, el id es del producto'
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            AddTransportCommand, el id es del producto
          required: true
          schema:
            $ref: '#/definitions/TransportCommand'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/command/transport/update:
    post:
      tags:
        - Comandos
      summary: >-
        Actualiza un transportista existente en el producto, el id es del
        producto
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            UpdateTransportCommand, el id es del producto
          required: true
          schema:
            $ref: '#/definitions/TransportCommand'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/command/transport/remove:
    post:
      tags:
        - Comandos
      summary: 'Elimina un transportista existente en el producto, el id es del producto'
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            RemoveTransportCommand, el id es del producto
          required: true
          schema:
            $ref: '#/definitions/RemoveTransportCommand'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/command/pricesSpecification:
    post:
      tags:
        - Comandos
      summary: >-
        Configura la especificacion de precios en el producto, el id es del
        producto
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            Necesitamos definir los parametros para el comando
            SetPricesSpecificationCommand, el id es del producto
          required: true
          schema:
            $ref: '#/definitions/SetPricesSpecificationCommand'
      responses:
        '200':
          description: successful operation
        '400':
          description: Comando no valido
  /product/command/addImage:
    post:
      tags:
        - Comandos
      summary: subir una imagen
      description: ''
      operationId: subir una imagen
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: id
          in: formData
          description: ID del producto
          required: true
          type: string
        - name: description
          in: formData
          description: descripcion de la imagen
          required: false
          type: string
        - name: caption
          in: formData
          description: caption de la imagen
          required: false
          type: string
        - name: uploadfile
          in: formData
          description: file to upload
          required: false
          type: file
      responses:
        '200':
          description: successful operation
  /product/:
    get:
      tags:
        - Product
      summary: Consulta los productos disponibles
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: operacion exitosa
        '404':
          description: recursos no encontrados
  '/product/{productId}':
    get:
      tags:
        - Product
      summary: Consulta un producto por su id
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: productId
          required: true
          description: identificador del producto
          schema:
            type: string
      responses:
        '200':
          description: operacion exitosa
        '404':
          description: recursos no encontrados
definitions:
  CreateProductCommand:
    type: object
    properties:
      reference:
        type: string
      ean_13:
        type: string
      isbn:
        type: string
      upc:
        type: string
  DeleteProductCommand:
    type: object
    properties:
      id:
        type: string
        description: id del producto
  RemoveProductLangCommand:
    type: object
    properties:
      id:
        type: string
        description: id del producto
      lang_code:
        type: string
  SetAvailabilityCommand:
    type: object
    properties:
      id:
        type: string
        description: id del producto
      quantity:
        type: integer
      minimal_quantity:
        type: integer
      online_only:
        type: boolean
      on_sale:
        type: boolean
      out_of_stock:
        type: boolean
      active:
        type: boolean
      available_for_order:
        type: boolean
      available_date:
        type: string
      visibility:
        type: string
        enum:
          - CATALOG
          - SEARCH
          - NONE
          - BOTH
      date_add:
        type: string
      date_upd:
        type: string
      quantity_discount:
        type: boolean
  ProductLang:
    type: object
    properties:
      id:
        type: string
        description: id del producto
      name:
        type: string
      description:
        type: string
      description_short:
        type: string
      link_rewrite:
        type: string
      meta_description:
        type: string
      meta_keywords:
        type: string
      meta_title:
        type: string
      available_now:
        type: string
      available_later:
        type: string
      lang_code:
        type: string
        description: codigo del idioma
  SetTransportSpecificationCommand:
    type: object
    properties:
      id:
        type: string
        description: id del producto
      width:
        type: integer
      height:
        type: integer
      depth:
        type: integer
      weight:
        type: integer
      additional_shipping_cost:
        type: integer
      transporters:
        type: array
        items:
          $ref: '#/definitions/Transporter'
  TransportCommand:
    type: object
    properties:
      id:
        type: string
        description: id del Producto
      transporter_id:
        type: string
        description: id del Trasportista
      name:
        type: string
      description:
        type: string
  Transporter:
    type: object
    properties:
      id:
        type: string
        description: id del Trasportista
      name:
        type: string
      description:
        type: string
  RemoveTransportCommand:
    type: object
    properties:
      id:
        type: string
        description: id del producto
      transporter_id:
        type: string
        description: id del transportista
  SetPricesSpecificationCommand:
    type: object
    properties:
      id:
        type: string
        description: id del producto
      id_taxt_rules_group:
        type: string
      price:
        type: integer
      whole_sale_price:
        type: integer
      unit_price_ratio:
        type: string
      show_price:
        type: boolean
      priorities_for_rules:
        type: array
        items:
          type: string
      ecotax:
        type: integer
      price_currency:
        type: string
      valid_from:
        type: string
      valid_through:
        type: string
      value_added_tax_included:
        type: boolean
      max_price:
        type: integer
      min_price:
        type: integer
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
